### ISSUE TITLE
exclude mounted folder from snapshot/backup

### ISSUE THREAD

**Issue by dddesign** [dianlight/addon-plex#11]
hi there
first: thanks a lot for this addon, mounting some network folder is what I missed in offical addon
question: if I do a snapshot by HA of this addon all network folder will be backup too. is there a way to exclude them?
thanks for any hints.

**Comment by lbouriez** [comment]
Hello, I think by adding these on the config.yaml should help:
![image](https://user-images.githubusercontent.com/4749766/156185175-21b557de-43be-4491-8186-7e5877f047e8.png)
