### ISSUE TITLE
How to install the Plex server update

### ISSUE THREAD

**Issue by jas8472** [dianlight/addon-plex#12]
# Plex server update

> (Plex server out if date)

## to be able to manually install the Plex media server.spk

> (Have a button in hassio add-on to install spk)

## can't find how to update

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (Add upload/install spk button)

**Comment by lbouriez** [comment]
Like the official addon, the addons needs to be updated regularly.
You can also fork it and change the plex version number in the Dockerfile
