### ISSUE TITLE
Error on Start: Port '1900' is already in use by something else on the host.

### ISSUE THREAD

**Issue by mattstegner** [dianlight/addon-plex#13]
# Problem/Motivation

> Installed the Plex add-on, turned off the Protected mode.  The install is on a RaspPi4, under 2021.12.07.  When starting the Add on, I get the error:
"Failed to start add-on
Port '1900' is already in use by something else on the host."

My router is a Unifi Dream Machine.  I also have Plex server running on a Mac Mini on my network, but it is disabled as I set up the HomeAssistant instance.
I has also previously installed the main Plex Add-on, but when I discovered that I could not get it to work with my NAS, I uninstalled and rebooted the HA instance.

## Expected behavior

> No Error

## Actual behavior

> Error message on start of the add on:
"Failed to start add-on
Port '1900' is already in use by something else on the host."

## Steps to reproduce

> 1.  Point to the repro.
2. Install Plex and NAS
3. Configure the yaml
4. Turn off Protected mode
5. Press start button
Result:  Error

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by pippo73** [comment]
Hi, have you found any solution?

**Comment by mattstegner** [comment]
No.  I abandoned Plex on that Pi and installed it on another Pi.
